import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Button } from "../../src/components/Button";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
export default function StoreDetail(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const insets=useSafeAreaInsets();const{session}=useAuth();const[store,setStore]=useState<any>();const[stock,setStock]=useState(0);const[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const r=await supabase.from("stores").select("*,markets(name,hub_address),seller_listings(stock_quantity,reserved_quantity,status)").eq("store_id",Number(id)).single();setStore(r.data);setStock((r.data?.seller_listings??[]).filter((x:any)=>x.status==="active").reduce((n:number,x:any)=>n+x.stock_quantity-x.reserved_quantity,0));setLoading(false)})()},[id]);const add=async()=>{if(!session)return router.push("/(auth)/sign-in" as never);const{data,error}=await supabase.rpc("increment_cart_item",{p_store_id:Number(id),p_increment:1});if(error)Alert.alert("เพิ่มไม่ได้",error.message);else Alert.alert("เพิ่มลงตะกร้าแล้ว",`ขณะนี้มี ${data} ${store.unit}`)};const chat=async()=>{if(!session)return router.push("/(auth)/sign-in" as never);const{data,error}=await supabase.from("chat_rooms").upsert({buyer_id:session.user.id,store_id:Number(id)},{onConflict:"buyer_id,store_id"}).select("room_id").single();if(error)Alert.alert(error.message);else router.push(`/chat/${data.room_id}` as never)};if(loading)return <View style={s.center}><ActivityIndicator color={Colors.greenPrimary}/></View>;if(!store)return <View style={s.center}><Text>ไม่พบร้านค้า</Text></View>;return <View style={s.root}><ScrollView contentContainerStyle={{paddingBottom:120}}>{store.image_url?<Image source={{uri:store.image_url}} style={s.image}/>:<View style={[s.image,s.placeholder]}><Ionicons name="basket" size={54} color={Colors.greenPrimary}/></View>}<TouchableOpacity style={[s.back,{top:insets.top+10}]} onPress={()=>router.back()}><Ionicons name="arrow-back" size={22}/></TouchableOpacity><View style={s.body}><Text style={s.market}>{store.markets?.name}</Text><Text style={s.title}>{store.name}</Text><Text style={s.product}>{store.product_name}</Text><Text style={s.desc}>{store.description}</Text><View style={s.info}><Text style={s.price}>฿{Number(store.unit_price).toLocaleString()} / {store.unit}</Text><Text style={s.stock}>พร้อมขาย {stock} {store.unit}</Text></View><View style={s.hub}><Ionicons name="cube-outline" size={20} color={Colors.greenPrimary}/><Text style={s.hubText}>ผู้ขายหลายรายส่งของมารวมที่ {store.markets?.hub_address} แล้วจัดส่งเป็นพัสดุเดียว</Text></View><TouchableOpacity onPress={chat}><Text style={s.chat}>แชตกับผู้ดูแลร้าน</Text></TouchableOpacity></View></ScrollView><View style={s.bottom}><Button title={stock>0?"เพิ่มลงตะกร้า":"สินค้าหมด"} disabled={stock<=0} onPress={add} style={{backgroundColor:Colors.goldPrimary}}/></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},center:{flex:1,alignItems:"center",justifyContent:"center"},image:{width:"100%",height:280},placeholder:{alignItems:"center",justifyContent:"center",backgroundColor:"#EAF1E9"},back:{position:"absolute",left:18,width:42,height:42,borderRadius:21,backgroundColor:"#FFFFFFDD",alignItems:"center",justifyContent:"center"},body:{padding:Spacing.lg},market:{fontFamily:"Kanit_500Medium",color:Colors.goldDark},title:{fontFamily:"Kanit_700Bold",fontSize:27,color:Colors.greenPrimary},product:{fontFamily:"Kanit_700Bold",fontSize:18,color:Colors.textDark},desc:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,lineHeight:21,marginTop:8},info:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginVertical:20},price:{fontFamily:"Kanit_700Bold",fontSize:22,color:Colors.greenPrimary},stock:{fontFamily:"Kanit_500Medium",color:Colors.textMedium},hub:{flexDirection:"row",gap:10,padding:Spacing.md,backgroundColor:"#EAF1E9",borderRadius:BorderRadius.lg},hubText:{flex:1,fontFamily:"Kanit_400Regular",color:Colors.greenDark},chat:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary,textAlign:"center",padding:18},bottom:{position:"absolute",left:0,right:0,bottom:0,padding:Spacing.md,backgroundColor:"white",borderTopWidth:1,borderTopColor:Colors.inputBorder}});
