import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { supabase } from "../../src/lib/supabase";
export default function MarketDetail(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const insets=useSafeAreaInsets();const[market,setMarket]=useState<any>();const[stores,setStores]=useState<any[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const[m,s]=await Promise.all([supabase.from("markets").select("*").eq("market_id",Number(id)).single(),supabase.from("stores").select("*,seller_listings(stock_quantity,reserved_quantity,status)").eq("market_id",Number(id)).eq("approval_status","approved")]);setMarket(m.data);setStores(s.data??[]);setLoading(false)})()},[id]);if(loading)return <View style={st.center}><ActivityIndicator color={Colors.greenPrimary}/></View>;if(!market)return <View style={st.center}><Text>ไม่พบตลาด</Text></View>;return <View style={st.root}><View style={[st.hero,{paddingTop:insets.top+16}]}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color="white"/></TouchableOpacity><Text style={st.heroTitle}>{market.name}</Text><Text style={st.heroDesc}>{market.description}</Text><View style={st.location}><Ionicons name="location-outline" size={16} color={Colors.goldPrimary}/><Text style={st.locationText}>{market.hub_address}</Text></View></View><ScrollView contentContainerStyle={st.content}><View style={st.row}><Text style={st.title}>ร้านค้าในชุมชน</Text><TouchableOpacity onPress={()=>router.push({pathname:"/seller/listings/join",params:{marketId:id}} as never)}><Text style={st.apply}>เปิดร้าน</Text></TouchableOpacity></View>{!stores.length?<Text style={st.empty}>ยังไม่มีร้านที่ผ่านการอนุมัติ</Text>:null}{stores.map(store=>{const stock=(store.seller_listings??[]).filter((x:any)=>x.status==="active").reduce((n:number,x:any)=>n+x.stock_quantity-x.reserved_quantity,0);return <TouchableOpacity key={store.store_id} style={st.card} onPress={()=>router.push(`/store/${store.store_id}` as never)}><View style={st.icon}><Ionicons name="basket" size={27} color={Colors.greenPrimary}/></View><View style={{flex:1}}><Text style={st.store}>{store.name}</Text><Text style={st.product}>{store.product_name} · ฿{Number(store.unit_price).toLocaleString()}/{store.unit}</Text><Text style={st.stock}>พร้อมขาย {stock} {store.unit}</Text></View><Ionicons name="chevron-forward" size={20} color={Colors.textMuted}/></TouchableOpacity>})}</ScrollView></View>}
const st=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},center:{flex:1,alignItems:"center",justifyContent:"center"},hero:{backgroundColor:Colors.greenPrimary,padding:Spacing.lg,paddingBottom:28,borderBottomLeftRadius:28,borderBottomRightRadius:28},heroTitle:{fontFamily:"Kanit_700Bold",fontSize:27,color:"white",marginTop:20},heroDesc:{fontFamily:"Kanit_400Regular",color:"#DDEBE2",marginTop:4},location:{flexDirection:"row",gap:6,marginTop:12},locationText:{fontFamily:"Kanit_400Regular",color:"white",flex:1},content:{padding:Spacing.lg},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:12},title:{fontFamily:"Kanit_700Bold",fontSize:20,color:Colors.textDark},apply:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary},card:{backgroundColor:"white",borderRadius:BorderRadius.lg,padding:Spacing.md,marginBottom:12,flexDirection:"row",alignItems:"center",gap:12,borderWidth:1,borderColor:Colors.inputBorder},icon:{width:54,height:54,borderRadius:16,backgroundColor:"#EAF1E9",alignItems:"center",justifyContent:"center"},store:{fontFamily:"Kanit_700Bold",color:Colors.textDark,fontSize:16},product:{fontFamily:"Kanit_400Regular",color:Colors.textMedium},stock:{fontFamily:"Kanit_500Medium",fontSize:12,color:Colors.greenPrimary},empty:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,textAlign:"center",marginTop:30}});
