import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { Button } from "../../../src/components/Button";
import { PermissionGate } from "../../../src/components/PermissionGate";
import { Colors, Spacing } from "../../../src/constants/theme";
import { useCapabilities } from "../../../src/hooks/useCapabilities";
import { supabase } from "../../../src/lib/supabase";
import { allocationStatusLabel } from "../../../src/lib/displayText";
export default function Allocations(){const permissions=useCapabilities();const[list,setList]=useState<any[]>([]);const load=()=>supabase.from("order_allocations").select("*,order_items(product_name,unit,orders(order_number))").order("created_at",{ascending:false}).then(({data})=>setList(data??[]));useEffect(()=>{void load()},[]);const ready=async(id:number)=>{const{error}=await supabase.rpc("mark_allocation_ready",{p_allocation_id:id});if(error)Alert.alert("แจ้งว่าสินค้าพร้อมไม่สำเร็จ","กรุณาลองใหม่อีกครั้ง");else await load()};return <PermissionGate allow={permissions.isSeller} loading={permissions.loading}><ScrollView contentContainerStyle={s.root}><Text style={s.title}>รายการสินค้าที่ต้องเตรียม</Text><Text style={s.help}>เตรียมสินค้าให้ครบตามจำนวน แล้วกดแจ้งเมื่อพร้อมให้เจ้าของตลาดมารับ</Text>{list.map(a=><View key={a.allocation_id} style={s.card}><Text style={s.name}>{a.order_items?.product_name} × {a.quantity} {a.order_items?.unit}</Text><Text style={s.meta}>{a.order_items?.orders?.order_number} · {allocationStatusLabel(a.status)}</Text>{a.status==="preparing"?<Button title="เตรียมเสร็จแล้ว พร้อมให้มารับ" size="sm" onPress={()=>ready(a.allocation_id)}/>:null}</View>)}</ScrollView></PermissionGate>}
const s=StyleSheet.create({root:{padding:Spacing.lg,paddingTop:60,backgroundColor:Colors.background,flexGrow:1},title:{fontFamily:"Kanit_700Bold",fontSize:25,color:Colors.greenPrimary},help:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,marginTop:4},card:{padding:16,backgroundColor:"white",borderRadius:16,marginTop:12},name:{fontFamily:"Kanit_700Bold"},meta:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,marginBottom:10}});
