import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Button } from "../../../src/components/Button";
import { PermissionGate } from "../../../src/components/PermissionGate";
import { Colors, Spacing } from "../../../src/constants/theme";
import { useCapabilities } from "../../../src/hooks/useCapabilities";
import { supabase } from "../../../src/lib/supabase";
export default function Stock(){const permissions=useCapabilities();const[list,setList]=useState<any[]>([]);const load=()=>supabase.from("seller_listings").select("*,stores(name,product_name,unit)").then(({data})=>setList(data??[]));useEffect(()=>{void load()},[]);const save=async(x:any)=>{const{error}=await supabase.rpc("update_my_listing_stock",{p_listing_id:x.listing_id,p_stock_quantity:Number(x.draft??x.stock_quantity),p_status:x.status});if(error)Alert.alert(error.message);else await load()};return <PermissionGate allow={permissions.isSeller||permissions.isStoreManager} loading={permissions.loading}><ScrollView contentContainerStyle={s.root}><Text style={s.title}>จัดการสต็อก</Text>{list.map((x,i)=><View style={s.card} key={x.listing_id}><Text style={s.name}>{x.stores?.product_name} · {x.stores?.name}</Text><Text style={s.reserved}>จองแล้ว {x.reserved_quantity} {x.stores?.unit}</Text><TextInput style={s.input} keyboardType="number-pad" value={String(x.draft??x.stock_quantity)} onChangeText={v=>setList(a=>a.map((y,j)=>j===i?{...y,draft:v}:y))}/><Button title="บันทึกสต็อก" size="sm" onPress={()=>save(x)}/></View>)}</ScrollView></PermissionGate>}
const s=StyleSheet.create({root:{padding:Spacing.lg,paddingTop:60,backgroundColor:Colors.background,flexGrow:1},title:{fontFamily:"Kanit_700Bold",fontSize:25,color:Colors.greenPrimary},card:{padding:16,backgroundColor:"white",borderRadius:16,marginTop:12},name:{fontFamily:"Kanit_700Bold"},reserved:{fontFamily:"Kanit_400Regular",color:Colors.textMuted},input:{backgroundColor:Colors.inputBackground,padding:10,marginVertical:10,fontFamily:"Kanit_400Regular"}});
