import { useLocalSearchParams } from "expo-router";
import React, { useEffect, useState } from "react";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppTextInput } from "../../src/components/AppTextInput";
import { KeyboardAwareView } from "../../src/components/KeyboardAware";
import { Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
export default function ChatRoom(){const{id}=useLocalSearchParams<{id:string}>();const{session}=useAuth();const[messages,setMessages]=useState<any[]>([]);const[text,setText]=useState("");const load=()=>supabase.from("chat_messages").select("*").eq("room_id",Number(id)).order("created_at").then(({data})=>setMessages(data??[]));useEffect(()=>{void load();const c=supabase.channel(`chat-${id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"chat_messages",filter:`room_id=eq.${id}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[id]);const send=async()=>{const body=text.trim();if(!body||!session)return;setText("");await supabase.from("chat_messages").insert({room_id:Number(id),sender_id:session.user.id,message:body})};return <KeyboardAwareView><View style={s.root}><ScrollView contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag">{messages.map(m=><View key={m.message_id} style={[s.bubble,m.sender_id===session?.user.id?s.mine:s.theirs]}><Text style={m.sender_id===session?.user.id?s.mineText:s.text}>{m.message}</Text></View>)}</ScrollView><View style={s.composer}><AppTextInput value={text} onChangeText={setText} style={s.input} placeholder="พิมพ์ข้อความ..."/><TouchableOpacity onPress={send}><Text style={s.send}>ส่ง</Text></TouchableOpacity></View></View></KeyboardAwareView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background,paddingTop:50},messages:{padding:Spacing.md},bubble:{padding:12,borderRadius:16,maxWidth:"80%",marginBottom:8},mine:{backgroundColor:Colors.greenPrimary,alignSelf:"flex-end"},theirs:{backgroundColor:"white",alignSelf:"flex-start"},text:{fontFamily:"Kanit_400Regular"},mineText:{fontFamily:"Kanit_400Regular",color:"white"},composer:{flexDirection:"row",padding:12,backgroundColor:"white",alignItems:"center",gap:10},input:{flex:1,backgroundColor:Colors.inputBackground,borderRadius:99,paddingHorizontal:16,fontFamily:"Kanit_400Regular"},send:{fontFamily:"Kanit_700Bold",color:Colors.greenPrimary}});
