/* eslint-disable react-hooks/set-state-in-effect */
import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Button } from "../../src/components/Button";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
type Area={code:string;name_th:string;postal_code?:string|null};
export default function ShippingAddress(){const{session}=useAuth();const[list,setList]=useState<any[]>([]);const[areas,setAreas]=useState<{p:Area[];d:Area[];s:Area[]}>({p:[],d:[],s:[]});const[p,setP]=useState<Area>();const[d,setD]=useState<Area>();const[sub,setSub]=useState<Area>();const[name,setName]=useState("");const[phone,setPhone]=useState("");const[line,setLine]=useState("");const load=async()=>{const r=await supabase.from("user_addresses").select("*,thai_subdistricts(name_th)").order("is_default",{ascending:false});setList(r.data??[])};useEffect(()=>{void load();supabase.from("thai_provinces").select("code,name_th").order("name_th").then(({data})=>setAreas(x=>({...x,p:data??[]})))},[]);useEffect(()=>{setD(undefined);setSub(undefined);setAreas(x=>({...x,d:[],s:[]}));if(p)supabase.from("thai_districts").select("code,name_th").eq("province_code",p.code).order("name_th").then(({data})=>setAreas(x=>({...x,d:data??[]})))},[p]);useEffect(()=>{setSub(undefined);setAreas(x=>({...x,s:[]}));if(d)supabase.from("thai_subdistricts").select("code,name_th,postal_code").eq("district_code",d.code).order("name_th").then(({data})=>setAreas(x=>({...x,s:data??[]})))},[d]);const save=async()=>{if(!session||!sub||!name||!phone||!line)return Alert.alert("กรอกข้อมูลให้ครบ");const{error}=await supabase.from("user_addresses").insert({user_id:session.user.id,recipient_name:name,phone,address_line:line,subdistrict_code:sub.code,postal_code:sub.postal_code??"",is_default:list.length===0});if(error)Alert.alert(error.message);else{setName("");setPhone("");setLine("");await load()}};const chips=(items:Area[],value:Area|undefined,set:(x:Area)=>void)=><ScrollView horizontal contentContainerStyle={s.chips}>{items.map(x=><TouchableOpacity key={x.code} style={[s.chip,value?.code===x.code&&s.active]} onPress={()=>set(x)}><Text style={[s.chipText,value?.code===x.code&&{color:"white"}]}>{x.name_th}</Text></TouchableOpacity>)}</ScrollView>;return <ScrollView style={s.root} contentContainerStyle={s.content}><Text style={s.title}>ที่อยู่จัดส่ง</Text>{list.map(a=><View key={a.address_id} style={s.card}><Text style={s.name}>{a.recipient_name} · {a.phone}</Text><Text style={s.detail}>{a.address_line} {a.thai_subdistricts?.name_th} {a.postal_code}</Text></View>)}<Text style={s.section}>เพิ่มที่อยู่</Text><TextInput style={s.input} placeholder="ชื่อผู้รับ" value={name} onChangeText={setName}/><TextInput style={s.input} placeholder="เบอร์โทร" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><TextInput style={s.input} placeholder="บ้านเลขที่ ถนน หมู่บ้าน" value={line} onChangeText={setLine}/><Text style={s.label}>จังหวัด</Text>{chips(areas.p,p,setP)}<Text style={s.label}>อำเภอ / เขต</Text>{chips(areas.d,d,setD)}<Text style={s.label}>ตำบล / แขวง</Text>{chips(areas.s,sub,setSub)}<Button title="บันทึกที่อยู่" onPress={save} style={{backgroundColor:Colors.goldPrimary,marginTop:20}}/></ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},content:{padding:Spacing.lg,paddingTop:60,paddingBottom:60},title:{fontFamily:"Kanit_700Bold",fontSize:25,color:Colors.greenPrimary},section:{fontFamily:"Kanit_700Bold",fontSize:18,marginTop:20},card:{backgroundColor:"white",padding:16,borderRadius:16,marginTop:10},name:{fontFamily:"Kanit_700Bold"},detail:{fontFamily:"Kanit_400Regular",color:Colors.textMuted},input:{backgroundColor:"white",padding:13,borderRadius:BorderRadius.md,marginTop:8,fontFamily:"Kanit_400Regular",borderWidth:1,borderColor:Colors.inputBorder},label:{fontFamily:"Kanit_500Medium",marginTop:14,marginBottom:6},chips:{gap:6},chip:{paddingHorizontal:12,paddingVertical:7,backgroundColor:"white",borderRadius:99,borderWidth:1,borderColor:Colors.inputBorder},active:{backgroundColor:Colors.greenPrimary},chipText:{fontFamily:"Kanit_400Regular",color:Colors.textMedium}});
