import AsyncStorage from "@react-native-async-storage/async-storage";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { CommerceCard } from "../../src/components/CommerceCard";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useNearby } from "../../src/hooks/useCommerce";

export default function HomeScreen() {
  const router=useRouter(); const insets=useSafeAreaInsets(); const {items,loading,error,refresh}=useNearby("","all");
  const [showWelcomeGuide, setShowWelcomeGuide] = useState(false);
  useEffect(() => { AsyncStorage.getItem("locomall-home-guide-dismissed-v1").then((value) => setShowWelcomeGuide(value !== "true")).catch(() => setShowWelcomeGuide(true)); }, []);
  const dismissWelcomeGuide = async () => { setShowWelcomeGuide(false); await AsyncStorage.setItem("locomall-home-guide-dismissed-v1", "true"); };
  const marketItems = items.filter((item) => item.entity_type === "market");
  const storeItems = items.filter((item) => item.entity_type === "store");
  return <View style={styles.container}>
    <View style={[styles.hero,{paddingTop:insets.top+14}]}><View><Text style={styles.brand}>Locomall</Text><Text style={styles.tagline}>ของดีจากชุมชน ใกล้คุณก่อนเสมอ</Text></View><View style={styles.headerActions}><TouchableOpacity style={styles.cart} onPress={()=>router.push("/guide" as never)} accessibilityLabel="เปิดคู่มือการใช้งาน"><Ionicons name="help-circle-outline" size={23} color={Colors.greenPrimary}/></TouchableOpacity><TouchableOpacity style={styles.cart} onPress={()=>router.push("/order/cart" as never)} accessibilityLabel="เปิดตะกร้าสินค้า"><Ionicons name="cart-outline" size={23} color={Colors.greenPrimary}/></TouchableOpacity></View></View>
    <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={refresh}/>}>
      <TouchableOpacity style={styles.search} onPress={()=>router.push("/(tabs)/nearby" as never)}><Ionicons name="search" size={20} color={Colors.textMuted}/><Text style={styles.searchText}>ค้นหาตลาดหรือร้านค้าใกล้ฉัน</Text></TouchableOpacity>
      {showWelcomeGuide ? <View style={styles.guideCard}><View style={styles.guideIcon}><Ionicons name="book-outline" size={24} color={Colors.greenPrimary}/></View><View style={{flex:1}}><Text style={styles.guideTitle}>เพิ่งเริ่มใช้ Locomall?</Text><Text style={styles.guideText}>ดูวิธีซื้อสินค้า เริ่มขาย และดูแลตลาดแบบทีละขั้นได้ที่คู่มือ</Text><TouchableOpacity onPress={()=>router.push("/guide" as never)}><Text style={styles.guideLink}>เปิดคู่มือการใช้งาน</Text></TouchableOpacity></View><TouchableOpacity onPress={dismissWelcomeGuide} accessibilityLabel="ปิดคำแนะนำ"><Ionicons name="close" size={20} color={Colors.textMuted}/></TouchableOpacity></View> : null}
      <View style={styles.heading}><View><Text style={styles.eyebrow}>เริ่มจากชุมชนใกล้คุณ</Text><Text style={styles.title}>ตลาดชุมชนใกล้บ้าน</Text></View><TouchableOpacity onPress={()=>router.push("/(tabs)/nearby" as never)}><Text style={styles.more}>ค้นหาเพิ่มเติม</Text></TouchableOpacity></View>
      {loading&&!items.length?<ActivityIndicator color={Colors.greenPrimary} style={{marginTop:40}}/>:null}{error?<Text style={styles.message}>โหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่อีกครั้ง</Text>:null}
      {!loading&&!error&&!items.length?<View style={styles.empty}><Ionicons name="leaf-outline" size={38} color={Colors.greenPrimary}/><Text style={styles.emptyTitle}>ยังไม่มีตลาดในพื้นที่</Text><Text style={styles.message}>ระบบจะขยายระยะค้นหาจาก 10 กม. ทีละ 5 กม. ให้อัตโนมัติเมื่อมีตลาดเปิดใช้งาน</Text></View>:null}
      {marketItems.slice(0,3).map(item=><CommerceCard key={`market-${item.entity_id}`} item={item} onPress={()=>router.push(`/market/${item.entity_id}` as never)}/>)}
      {storeItems.length ? <View style={styles.heading}><View><Text style={styles.eyebrow}>เลือกซื้อได้ทันที</Text><Text style={styles.title}>ร้านค้าและสินค้าใกล้คุณ</Text></View><TouchableOpacity onPress={()=>router.push("/(tabs)/nearby" as never)}><Text style={styles.more}>ดูทั้งหมด</Text></TouchableOpacity></View> : null}
      {storeItems.slice(0,6).map(item=><CommerceCard key={`store-${item.entity_id}`} item={item} onPress={()=>router.push(`/store/${item.entity_id}` as never)}/>)}
    </ScrollView>
  </View>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:Colors.background},hero:{backgroundColor:Colors.goldPrimary,paddingHorizontal:Spacing.lg,paddingBottom:Spacing.lg,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomLeftRadius:28,borderBottomRightRadius:28},brand:{fontFamily:"Spectral_700Bold",fontSize:30,color:Colors.greenPrimary},tagline:{fontFamily:"Kanit_400Regular",fontSize:13,color:Colors.greenDark},headerActions:{flexDirection:"row",gap:8},cart:{width:44,height:44,borderRadius:22,backgroundColor:Colors.cardBackground,alignItems:"center",justifyContent:"center"},content:{padding:Spacing.lg,paddingBottom:80},search:{height:50,borderRadius:BorderRadius.round,backgroundColor:Colors.cardBackground,borderWidth:1,borderColor:Colors.inputBorder,flexDirection:"row",alignItems:"center",gap:8,paddingHorizontal:Spacing.md},searchText:{fontFamily:"Kanit_400Regular",color:Colors.textMuted},guideCard:{flexDirection:"row",alignItems:"flex-start",gap:10,backgroundColor:"#F0F7F2",borderWidth:1,borderColor:"#CFE2D5",borderRadius:BorderRadius.lg,padding:14,marginTop:12},guideIcon:{width:40,height:40,borderRadius:20,backgroundColor:Colors.cardBackground,alignItems:"center",justifyContent:"center"},guideTitle:{fontFamily:"Kanit_700Bold",color:Colors.textDark},guideText:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,lineHeight:20},guideLink:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary,marginTop:5},heading:{flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",marginTop:Spacing.lg,marginBottom:Spacing.md},eyebrow:{fontFamily:"Kanit_500Medium",fontSize:11,color:Colors.goldDark},title:{fontFamily:"Kanit_700Bold",fontSize:22,color:Colors.greenPrimary},more:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary},message:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,textAlign:"center",marginTop:8},empty:{padding:Spacing.xl,alignItems:"center",backgroundColor:Colors.cardBackground,borderRadius:BorderRadius.lg,marginBottom:Spacing.lg},emptyTitle:{fontFamily:"Kanit_700Bold",fontSize:17,color:Colors.textDark,marginTop:8}});
