import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppTextInput } from "../../src/components/AppTextInput";
import { KeyboardAwareView } from "../../src/components/KeyboardAware";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { CommerceCard } from "../../src/components/CommerceCard";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useNearby } from "../../src/hooks/useCommerce";
export default function NearbyScreen(){const router=useRouter();const insets=useSafeAreaInsets();const[query,setQuery]=useState("");const[kind,setKind]=useState("all");const{items,loading,error}=useNearby(query,kind);return <KeyboardAwareView><View style={s.root}><View style={[s.head,{paddingTop:insets.top+12}]}><Text style={s.title}>ค้นหาใกล้ตัว</Text><View style={s.search}><Ionicons name="search" size={19}/><AppTextInput value={query} onChangeText={setQuery} placeholder="ตลาด ร้าน หรือสินค้า" style={s.input}/></View><View style={s.filters}>{[["all","ทั้งหมด"],["market","ตลาด"],["store","ร้านค้า"]].map(([value,label])=><TouchableOpacity key={value} onPress={()=>setKind(value)} style={[s.pill,kind===value&&s.active]}><Text style={[s.pillText,kind===value&&s.activeText]}>{label}</Text></TouchableOpacity>)}</View></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag">{loading?<ActivityIndicator color={Colors.greenPrimary}/>:null}{error?<Text style={s.error}>{error}</Text>:null}{items.length?<Text style={s.radius}>พบในระยะ {items[0].radius_km>=1000?"ทั่วประเทศ":`${items[0].radius_km} กม.`}</Text>:null}{items.map(item=><CommerceCard key={`${item.entity_type}-${item.entity_id}`} item={item} onPress={()=>router.push((item.entity_type==="market"?`/market/${item.entity_id}`:`/store/${item.entity_id}`) as never)}/>)}</ScrollView></View></KeyboardAwareView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},head:{paddingHorizontal:Spacing.lg,paddingBottom:Spacing.md,backgroundColor:Colors.goldPrimary,borderBottomLeftRadius:24,borderBottomRightRadius:24},title:{fontFamily:"Kanit_700Bold",fontSize:24,color:Colors.greenPrimary,marginBottom:8},search:{backgroundColor:"white",borderRadius:BorderRadius.round,height:46,paddingHorizontal:14,flexDirection:"row",alignItems:"center",gap:8},input:{flex:1,fontFamily:"Kanit_400Regular"},filters:{flexDirection:"row",gap:8,marginTop:10},pill:{paddingHorizontal:14,paddingVertical:6,borderRadius:99,backgroundColor:"#FFFFFF99"},active:{backgroundColor:Colors.greenPrimary},pillText:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary},activeText:{color:"white"},content:{padding:Spacing.lg,paddingBottom:80},radius:{fontFamily:"Kanit_500Medium",color:Colors.textMuted,marginBottom:10},error:{fontFamily:"Kanit_400Regular",color:Colors.danger,textAlign:"center"}});
