import { Ionicons } from "@expo/vector-icons";
import React from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useNotifications } from "../../src/hooks/useCommerce";
import { supabase } from "../../src/lib/supabase";
export default function NotificationScreen(){const insets=useSafeAreaInsets();const{items,loading,refresh}=useNotifications();const read=async(id:number)=>{await supabase.from("notifications").update({read_at:new Date().toISOString()}).eq("notification_id",id);await refresh()};return <View style={s.root}><View style={[s.head,{paddingTop:insets.top+12}]}><Text style={s.title}>การแจ้งเตือน</Text><Text style={s.sub}>อัปเดตคำขอและคำสั่งซื้อแบบเรียลไทม์</Text></View><ScrollView contentContainerStyle={s.content}>{loading?<ActivityIndicator color={Colors.greenPrimary}/>:null}{!loading&&!items.length?<View style={s.empty}><Ionicons name="notifications-off-outline" size={36} color={Colors.textMuted}/><Text style={s.emptyText}>ยังไม่มีการแจ้งเตือน</Text></View>:null}{items.map(n=><TouchableOpacity key={n.notification_id} style={[s.card,!n.read_at&&s.unread]} onPress={()=>read(n.notification_id)}><View style={s.icon}><Ionicons name={n.type==="approval"?"checkmark-circle-outline":"cube-outline"} size={22} color={Colors.greenPrimary}/></View><View style={{flex:1}}><Text style={s.itemTitle}>{n.title}</Text><Text style={s.body}>{n.body}</Text><Text style={s.date}>{new Date(n.created_at).toLocaleString("th-TH")}</Text></View></TouchableOpacity>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},head:{padding:Spacing.lg,backgroundColor:Colors.goldPrimary,borderBottomLeftRadius:24,borderBottomRightRadius:24},title:{fontFamily:"Kanit_700Bold",fontSize:24,color:Colors.greenPrimary},sub:{fontFamily:"Kanit_400Regular",color:Colors.greenDark},content:{padding:Spacing.lg,paddingBottom:80},card:{flexDirection:"row",gap:12,backgroundColor:"white",padding:Spacing.md,borderRadius:BorderRadius.lg,marginBottom:10,borderWidth:1,borderColor:Colors.inputBorder},unread:{borderLeftWidth:4,borderLeftColor:Colors.goldPrimary},icon:{width:40,height:40,borderRadius:20,backgroundColor:"#EAF1E9",alignItems:"center",justifyContent:"center"},itemTitle:{fontFamily:"Kanit_700Bold",color:Colors.textDark},body:{fontFamily:"Kanit_400Regular",color:Colors.textMedium},date:{fontFamily:"Kanit_400Regular",fontSize:11,color:Colors.textMuted,marginTop:5},empty:{alignItems:"center",marginTop:60},emptyText:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,marginTop:8}});
