import { Redirect, useRouter } from "expo-router";
import React from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { useOrders } from "../../src/hooks/useCommerce";
import { orderStatusLabel } from "../../src/lib/displayText";
export default function OrdersTab(){const router=useRouter();const insets=useSafeAreaInsets();const auth=useAuth();const{orders,loading,error}=useOrders();if(auth.loading)return <View style={[s.root,{alignItems:"center",justifyContent:"center"}]}><ActivityIndicator color={Colors.greenPrimary}/></View>;if(!auth.session)return <Redirect href="/(auth)/sign-in"/>;return <View style={s.root}><View style={[s.head,{paddingTop:insets.top+12}]}><Text style={s.title}>คำสั่งซื้อของฉัน</Text><Text style={s.sub}>ดูสถานะตั้งแต่ผู้ขายเตรียมสินค้า จนถึงวันที่คุณได้รับสินค้า</Text></View><ScrollView contentContainerStyle={s.content}>{loading?<ActivityIndicator color={Colors.greenPrimary}/>:null}{error?<Text style={s.error}>{error}</Text>:null}{!loading&&!orders.length?<Text style={s.empty}>ยังไม่มีคำสั่งซื้อ</Text>:null}{orders.map(o=><TouchableOpacity key={o.order_id} style={s.card} onPress={()=>router.push(`/order/${o.order_id}` as never)}><View style={s.row}><Text style={s.number}>{o.order_number}</Text><Text style={s.status}>{orderStatusLabel(o.status)}</Text></View>{o.order_items?.map((i:any)=><Text key={i.order_item_id} style={s.item}>{i.product_name} × {i.quantity}</Text>)}<View style={s.row}><Text style={s.date}>{new Date(o.created_at).toLocaleDateString("th-TH")}</Text><Text style={s.total}>฿{Number(o.total_amount).toLocaleString()}</Text></View></TouchableOpacity>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},head:{padding:Spacing.lg,backgroundColor:Colors.greenPrimary,borderBottomLeftRadius:24,borderBottomRightRadius:24},title:{fontFamily:"Kanit_700Bold",fontSize:24,color:"white"},sub:{fontFamily:"Kanit_400Regular",color:"#DDEBE2"},content:{padding:Spacing.lg,paddingBottom:80},card:{padding:Spacing.md,backgroundColor:"white",borderRadius:BorderRadius.lg,marginBottom:Spacing.md,borderWidth:1,borderColor:Colors.inputBorder},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},number:{fontFamily:"Kanit_700Bold",color:Colors.textDark},status:{fontFamily:"Kanit_500Medium",fontSize:11,color:Colors.greenPrimary,backgroundColor:"#EAF1E9",padding:5,borderRadius:8},item:{fontFamily:"Kanit_400Regular",color:Colors.textMedium,marginVertical:6},date:{fontFamily:"Kanit_400Regular",fontSize:12,color:Colors.textMuted},total:{fontFamily:"Kanit_700Bold",fontSize:18,color:Colors.greenPrimary},error:{color:Colors.danger,fontFamily:"Kanit_400Regular"},empty:{fontFamily:"Kanit_400Regular",textAlign:"center",color:Colors.textMuted,marginTop:40}});
