import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
export default function Profile(){const router=useRouter();const insets=useSafeAreaInsets();const{session,signOut}=useAuth();const[profile,setProfile]=useState<any>();const[isAdmin,setAdmin]=useState(false);useEffect(()=>{if(!session)return;Promise.all([supabase.from("profiles").select("display_name,full_name,username,user_img_url").eq("user_id",session.user.id).single(),supabase.from("platform_roles").select("role").eq("user_id",session.user.id).maybeSingle()]).then(([p,r])=>{setProfile(p.data);setAdmin(Boolean(r.data))})},[session]);const logout=()=>Alert.alert("ออกจากระบบ","เมื่อออกจากระบบ คุณจะต้องเข้าสู่ระบบอีกครั้งเพื่อซื้อสินค้าและดูข้อมูลบัญชี",[{text:"ยกเลิก",style:"cancel"},{text:"ออกจากระบบ",style:"destructive",onPress:async()=>{try{await signOut();router.replace("/(auth)/sign-in" as never);}catch{Alert.alert("ออกจากระบบไม่สำเร็จ","กรุณาตรวจสอบอินเทอร์เน็ตแล้วลองใหม่อีกครั้ง");}}}]);const actions=[{title:"แก้ไขโปรไฟล์",icon:"person-outline",route:"/profile/edit-profile"},{title:"ที่อยู่จัดส่ง",icon:"location-outline",route:"/profile/shipping-address"},{title:"เปลี่ยนรหัสผ่าน",icon:"lock-closed-outline",route:"/profile/change-password"},{title:"ศูนย์งานผู้ขาย",icon:"storefront-outline",route:"/seller/dashboard"},{title:"ขอเปิด Market",icon:"people-outline",route:"/market/create"}];return <View style={s.root}><View style={[s.hero,{paddingTop:insets.top+18}]}><View style={s.avatar}><Ionicons name="person" size={34} color={Colors.greenPrimary}/></View><Text style={s.name}>{session?(profile?.display_name||profile?.full_name||"ผู้ใช้ Locomall"):"ผู้ใช้ Locomall"}</Text><Text style={s.email}>{session?.user.email}</Text></View><ScrollView contentContainerStyle={s.content}>{actions.map(a=><TouchableOpacity key={a.route} style={s.row} onPress={()=>router.push(a.route as never)}><Ionicons name={a.icon as any} size={21} color={Colors.greenPrimary}/><Text style={s.action}>{a.title}</Text><Ionicons name="chevron-forward" size={18} color={Colors.textMuted}/></TouchableOpacity>)}{session&&isAdmin?<TouchableOpacity style={s.row} onPress={()=>router.push("/admin" as never)}><Ionicons name="shield-checkmark-outline" size={21} color={Colors.goldDark}/><Text style={s.action}>เปิดศูนย์ควบคุม Admin</Text><Ionicons name="chevron-forward" size={18}/></TouchableOpacity>:null}<TouchableOpacity style={s.logout} onPress={logout}><Text style={s.logoutText}>ออกจากระบบ</Text></TouchableOpacity></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},hero:{backgroundColor:Colors.greenPrimary,padding:Spacing.lg,paddingBottom:26,alignItems:"center",borderBottomLeftRadius:28,borderBottomRightRadius:28},avatar:{width:72,height:72,borderRadius:36,backgroundColor:"white",alignItems:"center",justifyContent:"center"},name:{fontFamily:"Kanit_700Bold",fontSize:22,color:"white",marginTop:10},email:{fontFamily:"Kanit_400Regular",color:"#DDEBE2"},content:{padding:Spacing.lg,paddingBottom:80},row:{padding:16,backgroundColor:"white",borderRadius:14,marginBottom:8,flexDirection:"row",alignItems:"center",gap:12},action:{fontFamily:"Kanit_500Medium",flex:1,color:Colors.textDark},logout:{padding:16,marginTop:12},logoutText:{fontFamily:"Kanit_500Medium",color:Colors.danger,textAlign:"center"}});
