/* eslint-disable react-hooks/set-state-in-effect */
import { Ionicons } from "@expo/vector-icons";
import * as Location from "expo-location";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Button } from "../../src/components/Button";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { supabase } from "../../src/lib/supabase";
type Area={code:string;name_th:string;postal_code?:string|null};
export default function LocationOnboarding(){const router=useRouter();const{refreshLocation}=useAuth();const[provinces,setProvinces]=useState<Area[]>([]);const[districts,setDistricts]=useState<Area[]>([]);const[subdistricts,setSubdistricts]=useState<Area[]>([]);const[province,setProvince]=useState<Area>();const[district,setDistrict]=useState<Area>();const[subdistrict,setSubdistrict]=useState<Area>();const[loading,setLoading]=useState(false);
useEffect(()=>{supabase.from("thai_provinces").select("code,name_th").order("name_th").then(({data})=>setProvinces(data??[]))},[]);
useEffect(()=>{setDistrict(undefined);setSubdistrict(undefined);setSubdistricts([]);if(province)supabase.from("thai_districts").select("code,name_th").eq("province_code",province.code).order("name_th").then(({data})=>setDistricts(data??[]));else setDistricts([])},[province]);
useEffect(()=>{setSubdistrict(undefined);if(district)supabase.from("thai_subdistricts").select("code,name_th,postal_code").eq("district_code",district.code).order("name_th").then(({data})=>setSubdistricts(data??[]));else setSubdistricts([])},[district]);
const save=async(useGps:boolean)=>{if(!province||!district||!subdistrict)return Alert.alert("กรุณาเลือกพื้นที่ให้ครบ");setLoading(true);let lat:number|undefined,lng:number|undefined,consent=false;if(useGps){const permission=await Location.requestForegroundPermissionsAsync();if(permission.status==="granted"){const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});lat=pos.coords.latitude;lng=pos.coords.longitude;consent=true;}}const{error}=await supabase.rpc("complete_location_onboarding",{p_province_code:province.code,p_district_code:district.code,p_subdistrict_code:subdistrict.code,p_lat:lat,p_lng:lng,p_gps_consent:consent});setLoading(false);if(error)return Alert.alert("บันทึกไม่สำเร็จ",error.message);await refreshLocation();router.replace("/(tabs)" as never)};
const choices=(title:string,items:Area[],selected:Area|undefined,onPress:(x:Area)=>void)=><View style={s.block}><Text style={s.label}>{title}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.choices}>{items.map(x=><TouchableOpacity key={x.code} style={[s.choice,selected?.code===x.code&&s.selected]} onPress={()=>onPress(x)}><Text style={[s.choiceText,selected?.code===x.code&&s.selectedText]}>{x.name_th}</Text></TouchableOpacity>)}</ScrollView></View>;
return <ScrollView style={s.root} contentContainerStyle={s.content}><View style={s.pin}><Ionicons name="location" size={32} color={Colors.greenPrimary}/></View><Text style={s.title}>เลือกชุมชนหลักของคุณ</Text><Text style={s.desc}>ใช้สำหรับแสดงตลาดใกล้ตัวและตรวจสอบสิทธิ์ผู้ขาย พิกัดจริงจะไม่แสดงต่อผู้ใช้อื่น</Text>{choices("จังหวัด",provinces,province,setProvince)}{choices("อำเภอ / เขต",districts,district,setDistrict)}{choices("ตำบล / แขวง",subdistricts,subdistrict,setSubdistrict)}<Button title="ใช้ตำแหน่ง GPS" onPress={()=>save(true)} loading={loading} style={s.primary}/><TouchableOpacity disabled={loading} onPress={()=>save(false)}><Text style={s.fallback}>ไม่อนุญาต GPS — ใช้จุดกึ่งกลางตำบลแทน</Text></TouchableOpacity></ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},content:{padding:Spacing.lg,paddingTop:70,paddingBottom:50},pin:{width:64,height:64,borderRadius:32,alignItems:"center",justifyContent:"center",backgroundColor:"#EAF1E9"},title:{fontFamily:"Kanit_700Bold",fontSize:26,color:Colors.greenPrimary,marginTop:18},desc:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,lineHeight:21,marginBottom:20},block:{marginBottom:18},label:{fontFamily:"Kanit_700Bold",fontSize:15,color:Colors.textDark,marginBottom:8},choices:{gap:8},choice:{paddingHorizontal:14,paddingVertical:9,borderRadius:BorderRadius.round,backgroundColor:"white",borderWidth:1,borderColor:Colors.inputBorder},selected:{backgroundColor:Colors.greenPrimary,borderColor:Colors.greenPrimary},choiceText:{fontFamily:"Kanit_400Regular",color:Colors.textMedium},selectedText:{color:"white"},primary:{marginTop:12,backgroundColor:Colors.goldPrimary},fallback:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary,textAlign:"center",padding:16}});
