drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to authenticated with check((select auth.uid())=user_id);

create index if not exists admin_audit_logs_actor_idx on public.admin_audit_logs(actor_id);
create index if not exists allocation_events_actor_idx on public.allocation_status_events(actor_id);
create index if not exists approval_events_actor_idx on public.approval_events(actor_id);
create index if not exists cart_items_store_idx on public.cart_items(store_id);
create index if not exists carts_market_idx on public.carts(market_id);
create index if not exists chat_messages_sender_idx on public.chat_messages(sender_id);
create index if not exists chat_rooms_store_idx on public.chat_rooms(store_id);
create index if not exists markets_owner_idx on public.markets(owner_id);
create index if not exists markets_province_idx on public.markets(province_code);
create index if not exists markets_district_idx on public.markets(district_code);
create index if not exists markets_subdistrict_idx on public.markets(subdistrict_code);
create index if not exists allocations_listing_idx on public.order_allocations(listing_id);
create index if not exists allocations_item_idx on public.order_allocations(order_item_id);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_store_idx on public.order_items(store_id);
create index if not exists orders_address_idx on public.orders(address_id);
create index if not exists platform_roles_granted_by_idx on public.platform_roles(granted_by);
create index if not exists seller_listings_seller_idx on public.seller_listings(seller_id);
create index if not exists seller_applications_applicant_idx on public.store_seller_applications(applicant_id);
create index if not exists seller_applications_reviewer_idx on public.store_seller_applications(reviewed_by);
create index if not exists stores_manager_idx on public.stores(manager_id);
create index if not exists thai_districts_province_idx on public.thai_districts(province_code);
create index if not exists thai_subdistricts_district_idx on public.thai_subdistricts(district_code);
create index if not exists thai_subdistricts_province_idx on public.thai_subdistricts(province_code);
create index if not exists user_addresses_subdistrict_idx on public.user_addresses(subdistrict_code);
create index if not exists user_addresses_user_idx on public.user_addresses(user_id);
create index if not exists user_locations_province_idx on public.user_locations(province_code);
create index if not exists user_locations_district_idx on public.user_locations(district_code);
create index if not exists user_locations_subdistrict_idx on public.user_locations(subdistrict_code);
