import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { Button } from "../../src/components/Button";
import { Colors, Spacing } from "../../src/constants/theme";
import { supabase } from "../../src/lib/supabase";
const steps=["awaiting_preparation","preparing","at_hub","consolidated","shipped","delivered"];
const labels:Record<string,string>={awaiting_preparation:"รับคำสั่งซื้อ",preparing:"ผู้ขายกำลังเตรียม",at_hub:"สินค้าถึงจุดรวม",consolidated:"รวมเป็นพัสดุเดียว",shipped:"กำลังจัดส่ง",delivered:"ส่งสำเร็จ",cancelled:"ยกเลิกแล้ว"};
export default function OrderDetail(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const[order,setOrder]=useState<any>();const load=()=>supabase.from("orders").select("*,markets(name,hub_address),order_items(*,order_allocations(*))").eq("order_id",Number(id)).single().then(({data})=>setOrder(data));useEffect(()=>{void load()},[id]);const cancel=async()=>{const{error}=await supabase.rpc("cancel_order",{p_order_id:Number(id),p_reason:"ยกเลิกโดยผู้ซื้อ"});if(error)Alert.alert(error.message);else await load()};const confirm=async()=>{const{error}=await supabase.rpc("confirm_delivery",{p_order_id:Number(id)});if(error)Alert.alert(error.message);else await load()};if(!order)return <View style={s.center}><Text>กำลังโหลด...</Text></View>;const current=steps.indexOf(order.status);return <ScrollView contentContainerStyle={s.root}><Text style={s.number}>{order.order_number}</Text><Text style={s.market}>{order.markets?.name}</Text><View style={s.timeline}>{steps.map((x,i)=><View key={x} style={s.step}><View style={[s.dot,i<=current&&s.done]}/><Text style={[s.stepText,i<=current&&s.doneText]}>{labels[x]}</Text></View>)}</View>{order.order_items.map((item:any)=><View style={s.card} key={item.order_item_id}><Text style={s.item}>{item.product_name} × {item.quantity} {item.unit}</Text><Text style={s.price}>฿{Number(item.total_amount).toLocaleString()}</Text><Text style={s.alloc}>กระจายให้ผู้ขาย {item.order_allocations.length} ราย</Text></View>)}<View style={s.totalRow}><Text style={s.item}>ยอดรวม COD</Text><Text style={s.total}>฿{Number(order.total_amount).toLocaleString()}</Text></View>{order.tracking_number?<View style={s.tracking}><Text style={s.item}>เลขติดตาม: {order.tracking_number}</Text><Text style={s.alloc}>{order.courier_name}</Text></View>:null}{order.status==="shipped"?<Button title="ยืนยันว่าได้รับสินค้าแล้ว" onPress={confirm}/>:null}{["awaiting_preparation","preparing","at_hub","consolidated"].includes(order.status)?<Button title="ยกเลิกคำสั่งซื้อ" variant="outline" onPress={cancel} style={{marginTop:10}}/>:null}</ScrollView>}
const s=StyleSheet.create({root:{padding:Spacing.lg,paddingTop:60,paddingBottom:60,backgroundColor:Colors.background,flexGrow:1},center:{flex:1,alignItems:"center",justifyContent:"center"},number:{fontFamily:"Kanit_700Bold",fontSize:24,color:Colors.greenPrimary},market:{fontFamily:"Kanit_400Regular",color:Colors.textMuted},timeline:{marginVertical:22},step:{flexDirection:"row",alignItems:"center",gap:10,marginBottom:12},dot:{width:15,height:15,borderRadius:8,backgroundColor:Colors.inputBorder},done:{backgroundColor:Colors.greenPrimary},stepText:{fontFamily:"Kanit_400Regular",color:Colors.textMuted},doneText:{color:Colors.textDark,fontFamily:"Kanit_500Medium"},card:{backgroundColor:"white",padding:16,borderRadius:16,marginBottom:10},item:{fontFamily:"Kanit_700Bold"},price:{fontFamily:"Kanit_700Bold",color:Colors.greenPrimary,fontSize:18},alloc:{fontFamily:"Kanit_400Regular",fontSize:12,color:Colors.textMuted},totalRow:{flexDirection:"row",justifyContent:"space-between",paddingVertical:16},total:{fontFamily:"Kanit_700Bold",fontSize:22,color:Colors.greenPrimary},tracking:{padding:16,backgroundColor:"#EAF1E9",borderRadius:16,marginBottom:16}});
