import { useLocalSearchParams } from "expo-router";
import React, { useCallback, useEffect, useState } from "react";
import { Alert, Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { Button } from "../../src/components/Button";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { useAuth } from "../../src/context/AuthContext";
import { formatThaiDateTime } from "../../src/lib/date";
import { translateDatabaseError } from "../../src/lib/databaseError";
import { supabase } from "../../src/lib/supabase";

const deliverySteps = ["awaiting_preparation", "preparing", "at_hub", "consolidated", "shipped", "delivered"];
const pickupSteps = ["awaiting_preparation", "preparing", "at_hub", "delivered"];
const deliveryLabels: Record<string, string> = { awaiting_preparation: "รับคำสั่งซื้อ", preparing: "ผู้ขายกำลังเตรียม", at_hub: "สินค้าถึงจุดรวม", consolidated: "รวมเป็นพัสดุเดียว", shipped: "กำลังจัดส่ง", delivered: "รับสินค้าแล้ว", cancelled: "ยกเลิกแล้ว" };
const pickupLabels: Record<string, string> = { awaiting_preparation: "รับคำสั่งซื้อ", preparing: "ผู้ขายกำลังเตรียม", at_hub: "สินค้าถึงจุดรวม พร้อมให้รับสินค้า", delivered: "รับสินค้าแล้ว", cancelled: "ยกเลิกแล้ว" };
const buyerDeliveryLabels: Record<string, string> = { awaiting_preparation: "รอผู้ขายรับคำสั่งซื้อ", preparing: "ผู้ขายกำลังเตรียมสินค้าให้คุณ", at_hub: "สินค้าของคุณถึงจุดรวม", consolidated: "รวมสินค้าเป็นพัสดุของคุณแล้ว", shipped: "สินค้ากำลังส่งมาหาคุณ", delivered: "คุณได้รับสินค้าแล้ว", cancelled: "คำสั่งซื้อของคุณถูกยกเลิก" };
const buyerPickupLabels: Record<string, string> = { awaiting_preparation: "รอผู้ขายรับคำสั่งซื้อ", preparing: "ผู้ขายกำลังเตรียมสินค้าให้คุณ", at_hub: "สินค้าพร้อมให้คุณรับที่จุดรวม", delivered: "คุณได้รับสินค้าแล้ว", cancelled: "คำสั่งซื้อของคุณถูกยกเลิก" };

export default function OrderDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useAuth(); const [order, setOrder] = useState<any>(); const [loading, setLoading] = useState(false);
  const load = useCallback(() => supabase.from("orders").select("*,markets(name,hub_address),order_items(*,stores(name,image_url))").eq("order_id", Number(id)).single().then(({ data }) => setOrder(data)), [id]);
  useEffect(() => { void load(); }, [load]);
  const cancel = async () => { setLoading(true); const { error } = await supabase.rpc("cancel_order", { p_order_id: Number(id), p_reason: "ยกเลิกโดยผู้ซื้อ" }); setLoading(false); if (error) Alert.alert("ยกเลิกไม่สำเร็จ", translateDatabaseError(error)); else await load(); };
  const confirm = () => Alert.alert("ยืนยันการรับสินค้า", order?.fulfillment_method === "pickup" ? "ยืนยันว่าคุณได้รับสินค้าจากจุดรวมเรียบร้อยแล้ว" : "ยืนยันว่าคุณได้รับพัสดุเรียบร้อยแล้ว", [{ text: "ยกเลิก", style: "cancel" }, { text: "ยืนยัน", onPress: async () => { setLoading(true); const { error } = await supabase.rpc("confirm_delivery", { p_order_id: Number(id) }); setLoading(false); if (error) Alert.alert("ยืนยันไม่สำเร็จ", translateDatabaseError(error)); else { Alert.alert("ยืนยันรับสินค้าแล้ว"); await load(); } } }]);
  if (!order) return <View style={styles.center}><Text>กำลังโหลด...</Text></View>;
  const pickup = order.fulfillment_method === "pickup"; const isBuyer = session?.user.id === order.buyer_id; const steps = pickup ? pickupSteps : deliverySteps; const labels = isBuyer ? (pickup ? buyerPickupLabels : buyerDeliveryLabels) : (pickup ? pickupLabels : deliveryLabels); const current = steps.indexOf(order.status);
  const canConfirm = isBuyer && ((pickup && order.status === "at_hub") || (!pickup && order.status === "shipped"));
  return <ScrollView contentContainerStyle={styles.root}>
    <Text style={styles.number}>{order.order_number}</Text><Text style={styles.market}>{order.markets?.name}</Text><Text style={styles.date}>วันที่สั่ง {formatThaiDateTime(order.created_at)}</Text>
    <View style={styles.method}><Text style={styles.methodTitle}>{pickup ? "นัดรับที่จุดรวมสินค้า" : "จัดส่งถึงที่อยู่"}</Text><Text style={styles.methodDetail}>{pickup ? `${order.markets?.hub_address}${order.pickup_distance_km ? ` · ${order.pickup_distance_km} กม.` : ""}` : "รวมส่งเป็นพัสดุเดียว"}</Text></View>
    <View style={styles.timeline}>{steps.map((step, index) => <View key={step} style={styles.step}><View style={[styles.dot, index <= current && styles.done]} /><Text style={[styles.stepText, index <= current && styles.doneText]}>{labels[step]}</Text></View>)}</View>
    {order.order_items.map((item: any) => <View style={styles.card} key={item.order_item_id}>{item.product_image_url||item.stores?.image_url?<Image source={{uri:item.product_image_url||item.stores?.image_url}} style={styles.productImage}/>:null}<View style={styles.productBody}><Text style={styles.item}>{item.product_name}</Text><Text style={styles.store}>ร้าน {item.stores?.name ?? "ร้านค้า"}</Text><View style={styles.itemDetail}><Text style={styles.alloc}>{item.quantity} {item.unit} × ฿{Number(item.unit_price).toLocaleString()}</Text><Text style={styles.price}>฿{Number(item.total_amount).toLocaleString()}</Text></View></View></View>)}
    <View style={styles.totalRow}><Text style={styles.item}>ยอดชำระเมื่อได้รับสินค้า</Text><Text style={styles.total}>฿{Number(order.total_amount).toLocaleString()}</Text></View>
    {order.tracking_number ? <View style={styles.tracking}><Text style={styles.item}>เลขติดตาม: {order.tracking_number}</Text><Text style={styles.alloc}>{order.courier_name}</Text></View> : null}
    {canConfirm ? <Button title={pickup ? "ยืนยันว่าได้รับสินค้าที่จุดรวมแล้ว" : "ยืนยันว่าได้รับสินค้าแล้ว"} onPress={confirm} loading={loading} /> : null}
    {!isBuyer && ((pickup && order.status === "at_hub") || (!pickup && order.status === "shipped")) ? <Text style={styles.onlyBuyer}>รอผู้ซื้อยืนยันการรับสินค้า</Text> : null}
    {isBuyer && ["awaiting_preparation", "preparing", "at_hub", "consolidated"].includes(order.status) ? <Button title="ยกเลิกคำสั่งซื้อ" variant="outline" onPress={cancel} loading={loading} style={{ marginTop: 10 }} /> : null}
  </ScrollView>;
}

const styles = StyleSheet.create({ root: { padding: Spacing.lg, paddingTop: 60, paddingBottom: 60, backgroundColor: Colors.background, flexGrow: 1 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, number: { fontFamily: "Kanit_700Bold", fontSize: 24, color: Colors.greenPrimary }, market: { fontFamily: "Kanit_500Medium", color: Colors.textMedium }, date: { fontFamily: "Kanit_400Regular", color: Colors.textMuted, fontSize: 12 }, method: { backgroundColor: "#FFF5D9", borderRadius: BorderRadius.lg, padding: 14, marginTop: 14 }, methodTitle: { fontFamily: "Kanit_700Bold", color: Colors.textDark }, methodDetail: { fontFamily: "Kanit_400Regular", color: Colors.textMuted }, timeline: { marginVertical: 22 }, step: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 }, dot: { width: 15, height: 15, borderRadius: 8, backgroundColor: Colors.inputBorder }, done: { backgroundColor: Colors.greenPrimary }, stepText: { fontFamily: "Kanit_400Regular", color: Colors.textMuted }, doneText: { color: Colors.textDark, fontFamily: "Kanit_500Medium" }, card: { backgroundColor: "white", padding: 12, borderRadius: 16, marginBottom: 10, flexDirection: "row", gap: 12 }, productImage: { width: 88, height: 88, borderRadius: 12, backgroundColor: "#EAF1E9" }, productBody: { flex: 1 }, item: { fontFamily: "Kanit_700Bold" }, store: { fontFamily: "Kanit_400Regular", color: Colors.textMuted, fontSize: 13 }, itemDetail: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 }, price: { fontFamily: "Kanit_700Bold", color: Colors.greenPrimary, fontSize: 18 }, alloc: { fontFamily: "Kanit_400Regular", fontSize: 12, color: Colors.textMuted }, totalRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 16 }, total: { fontFamily: "Kanit_700Bold", fontSize: 22, color: Colors.greenPrimary }, tracking: { padding: 16, backgroundColor: "#EAF1E9", borderRadius: 16, marginBottom: 16 }, onlyBuyer: { fontFamily: "Kanit_500Medium", color: Colors.textMuted, textAlign: "center", padding: 14 } });
