/* eslint-disable react-hooks/set-state-in-effect */
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Button } from "../../src/components/Button";
import { BorderRadius, Colors, Spacing } from "../../src/constants/theme";
import { supabase } from "../../src/lib/supabase";
export default function Cart(){const router=useRouter();const insets=useSafeAreaInsets();const[cart,setCart]=useState<any>();const load=async()=>{const r=await supabase.from("carts").select("*,cart_items(*,stores(*))").maybeSingle();setCart(r.data)};useEffect(()=>{void load()},[]);const change=async(storeId:number,q:number)=>{const{error}=q<=0?await supabase.rpc("remove_cart_item",{p_store_id:storeId}):await supabase.rpc("upsert_cart_item",{p_store_id:storeId,p_quantity:q});if(error)Alert.alert("แก้ไขจำนวนสินค้าไม่สำเร็จ","กรุณาลองใหม่อีกครั้ง");await load()};const total=(cart?.cart_items??[]).reduce((n:number,x:any)=>n+x.quantity*Number(x.stores.unit_price),0);return <View style={s.root}><View style={[s.head,{paddingTop:insets.top+10}]}><TouchableOpacity onPress={()=>router.back()}><Ionicons name="arrow-back" size={24}/></TouchableOpacity><Text style={s.title}>ตะกร้าสินค้า</Text><View style={{width:24}}/></View><ScrollView contentContainerStyle={s.content}>{!cart?.cart_items?.length?<Text style={s.empty}>ยังไม่มีสินค้าในตะกร้า</Text>:cart.cart_items.map((x:any)=><View key={x.cart_item_id} style={s.card}><View style={{flex:1}}><Text style={s.name}>{x.stores.product_name}</Text><Text style={s.store}>{x.stores.name}</Text><Text style={s.price}>฿{Number(x.stores.unit_price).toLocaleString()} / {x.stores.unit}</Text></View><View style={s.qty}><TouchableOpacity onPress={()=>change(x.store_id,x.quantity-1)}><Ionicons name="remove-circle-outline" size={25}/></TouchableOpacity><Text style={s.count}>{x.quantity}</Text><TouchableOpacity onPress={()=>change(x.store_id,x.quantity+1)}><Ionicons name="add-circle" size={25} color={Colors.greenPrimary}/></TouchableOpacity></View></View>)}</ScrollView>{cart?.cart_items?.length?<View style={s.bottom}><View style={s.totalRow}><Text style={s.totalLabel}>ยอดรวม</Text><Text style={s.total}>฿{total.toLocaleString()}</Text></View><Button title="เลือกวิธีรับสินค้าและสั่งซื้อ" onPress={()=>router.push("/order/checkout" as never)} style={{backgroundColor:Colors.goldPrimary}}/></View>:null}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.background},head:{padding:Spacing.lg,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:Colors.goldPrimary},title:{fontFamily:"Kanit_700Bold",fontSize:21,color:Colors.greenPrimary},content:{padding:Spacing.lg,paddingBottom:150},card:{flexDirection:"row",alignItems:"center",backgroundColor:"white",padding:Spacing.md,borderRadius:BorderRadius.lg,marginBottom:12,borderWidth:1,borderColor:Colors.inputBorder},name:{fontFamily:"Kanit_700Bold",fontSize:17},store:{fontFamily:"Kanit_400Regular",color:Colors.textMuted},price:{fontFamily:"Kanit_500Medium",color:Colors.greenPrimary},qty:{flexDirection:"row",alignItems:"center",gap:9},count:{fontFamily:"Kanit_700Bold"},empty:{fontFamily:"Kanit_400Regular",color:Colors.textMuted,textAlign:"center",marginTop:50},bottom:{position:"absolute",bottom:0,left:0,right:0,padding:Spacing.md,backgroundColor:"white",borderTopWidth:1,borderTopColor:Colors.inputBorder},totalRow:{flexDirection:"row",justifyContent:"space-between",marginBottom:10},totalLabel:{fontFamily:"Kanit_500Medium"},total:{fontFamily:"Kanit_700Bold",fontSize:21,color:Colors.greenPrimary}});
